---
- hosts: localhost
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: apt-get install python-simplejson -y
  tasks:
    - name: Update
      apt:
        update_cache: yes
        state: latest
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - openjdk-8-jdk
        - maven
        - wget
    - script: /home/ubuntu/script.sh
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      register: shellout
    - debug: var=shellout
    - file:
        state: absent
        path: /opt/Java-Mysql-Simple-Login-Web-application
    - file:
        state: absent
        path: /opt/apache-tomcat-8.5.33
    - git:
        repo: 'https://github.com/Meghanakanakavidu/Java-Mysql-Simple-Login-Web-application.git'
        dest: /opt/Java-Mysql-Simple-Login-Web-application
    - command: mvn clean install
      args:
        chdir: /opt/Java-Mysql-Simple-Login-Web-application
    - unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.33/bin/apache-tomcat-8.5.33.tar.gz
        dest: /opt
        remote_src: yes
#    - command: ./startup.sh
#      args:
#        chdir: /tmp/apache-tomcat-8.5.33/bin

    - copy:
        src: /opt/Java-Mysql-Simple-Login-Web-application/target/LoginWebApp.war
        dest: /opt/apache-tomcat-8.5.33/webapps/LoginWebApp.war
        remote_src: yes

    - name: "Starting Apache server"
      command: nohup /opt/apache-tomcat-8.5.33/bin/startup.sh

    - name: Check grep
      sudo: yes
      run_once: true
  #when: ansible_hostname !=  "inception-{{ vms_subdomain }}"
      shell: cat /opt/apache-tomcat-8.5.33/logs/catalina.out | grep "Server startup"
      register: command_res
  #with_dict: "{{ microservices }}"
      until: "command_res.rc == 0"
      failed_when: "'NOT' in command_res.stdout"
      retries: 100
      delay: 10
    - name: Check the output
      debug: var=command_res
