---
- hosts: nginx
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: apt-get install python-simplejson -y
  tasks:
    - name: Install a list of packages
      apt:
        update_cache: yes
        state: latest
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - openjdk-8-jdk
        - maven
        - wget
    - script: /root/playbooks/script.sh
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      register: shellout
    - debug: var=shellout
    - file:
        state: absent
        path: /tmp/Java-Mysql-Simple-Login-Web-application
    - file:
        state: absent
        path: /tmp/apache-tomcat-8.5.33
    - git:
        repo: 'https://github.com/Meghanakanakavidu/Java-Mysql-Simple-Login-Web-application.git'
        dest: /tmp/Java-Mysql-Simple-Login-Web-application
    - command: mvn clean install
      args:
        chdir: /tmp/Java-Mysql-Simple-Login-Web-application
    - unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.33/bin/apache-tomcat-8.5.33.tar.gz
        dest: /tmp
        remote_src: yes
#    - command: ./startup.sh
#      args:
#        chdir: /tmp/apache-tomcat-8.5.33/bin

    - copy:
        src: /tmp/Java-Mysql-Simple-Login-Web-application/target/LoginWebApp.war
        dest: /tmp/apache-tomcat-8.5.33/webapps/LoginWebApp.war
        remote_src: yes

    - name: "Starting Apache server"
      command: nohup /tmp/apache-tomcat-8.5.33/bin/startup.sh
