---
- hosts: nginx
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: apt-get install python-simplejson -y
  tasks:
    - name: Install a list of packages
      apt:
        update_cache: yes
        state: latest
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - openjdk-8-jdk
        - maven
        - tomcat8
        - tomcat8-admin
    - name: environment
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      shell: "echo $JAVA_HOME"
    - file:
        state: absent
        path: /tmp/AssigningTask
    - git:
        repo: 'https://github.com/iankesh/AssigningTask.git'
        dest: /tmp/AssigningTask
    - command: mvn clean install -Dmaven.test.skip=true
      args:
        chdir: /tmp/AssigningTask

